### ISSUE TITLE
Failing to build "strong-globalize".

### ISSUE THREAD

**Issue by paulogdm** [zeit/ncc#76] opened 2018-11-27 18:11 UTC
## Start
package.json
```json
{
  "dependencies": {
    "strong-globalize": "4.1.2"
  }
}
```

index.js
```
const fail = require('strong-globalize')
module.exports = fail
```

## Reproducing
```sh
$ npm i
$ ncc run index.js
```

## Output
```sh
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist" attempted to require "cldr" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist" attempted to require "cldr/event" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/supplemental" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/event" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/event" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/supplemental" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/event" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/supplemental" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/event" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/supplemental" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/event" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/event" but could not be resolved, assuming external.
ncc: Module directory "/home/paulogdm/Codes/tmp/nutstore_min_debug-master/tmp/node_modules/globalize/dist/globalize" attempted to require "cldr/supplemental" but could not be resolved, assuming external.
1084kB  /index.js   [1154ms]
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'cldr'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/12be0a0a6e869/index.js:538:18)
    at __webpack_require__ (/tmp/12be0a0a6e869/index.js:21:30)
    at /tmp/12be0a0a6e869/index.js:126:4
    at Object.<anonymous> (/tmp/12be0a0a6e869/index.js:133:2)
    at __webpack_require__ (/tmp/12be0a0a6e869/index.js:21:30)
    at Object.<anonymous> (/tmp/12be0a0a6e869/index.js:7594:18)
```
Original topic: https://spectrum.chat/?t=98452abc-a7ce-4a11-8529-9fb6db1cf690

**Comment by rauchg** [comment] 2018-11-27 19:06
Dupe of #68 it seems

**Closed by rauchg** 2018-11-27 19:06 UTC

**Comment by gijo-varghese** [comment] 2018-11-28 09:48
@paulogdm are you using Loopback?

**Comment by heshamelmasry77** [comment] 2019-05-27 00:08
@gijo-varghese  i am using loopback and i have the same issue do you have a solution ?

**Comment by gijo-varghese** [comment] 2019-05-27 01:57
No luck!
