### ISSUE TITLE
Puppeteer support

### ISSUE THREAD

**Issue by zababurinsv** [zeit/ncc#384] opened 2019-05-11 20:46 UTC
My now.json
{
"version": 2,
"name": "request:page",
"builds": [
{ "src": "/index.js", "use": "
@now
/node", "config": { "maxLambdaSize": "40mb" } }
],
"routes": [
{"src": "/","dest": "/index.js" }
]
}

My index.js

const chrome = require('chrome-aws-lambda');
const puppeteer = require('puppeteer-core');
export default async (req, res) => {

let body = '';
req.on('data', chunk => {
    body += chunk.toString();
});
req.on('end', async () => {
    console.log('~~~~~~~~1~~~~~~~~~~')
    const browser = await puppeteer.launch({
       args: chrome.args,
       executablePath: await chrome.executablePath,
       headless: chrome.headless,
    });
    console.log('~~~~~~~~~2~~~~~~~~~')
    let page = await browser.newPage();
    await page.goto('https://index-2d7a4.firebaseapp.com', {waitUntil: 'networkidle0'} );
    await page.content();
    console.log('~~~~~~~~~~3~~~~~~~~')
 let status =  await page.evaluate( (body) => {
        document.querySelector('varan-input').innerText = body
        return true
    },body)
    console.log('~~~~~~~~~~4~~~~~~~~', status)
    await browser.close();
    res.end(body)
})
};

And it's not work ((

Log

2019-05-11T20:31:45.506Z success Saved lockfile.
2019-05-11T20:31:45.507Z warning No license field
2019-05-11T20:31:45.510Z success Saved 7 new dependencies.
2019-05-11T20:31:45.510Z info Direct dependencies
2019-05-11T20:31:45.511Z └─ 
@now
/node@0.7.2
2019-05-11T20:31:45.511Z info All dependencies
2019-05-11T20:31:45.511Z ├─ 
@now
/node-bridge@1.1.2
├─ 
@now
/node@0.7.2
├─ 
@zeit
/ncc@0.18.5
├─ fs-extra@7.0.1
├─ graceful-fs@4.1.15
├─ jsonfile@4.0.0
└─ universalify@0.1.2
2019-05-11T20:31:45.512Z Done in 2.20s.
2019-05-11T20:31:48.835Z running builder.exports.build...
2019-05-11T20:31:48.835Z downloading user files...
2019-05-11T20:31:49.223Z installing dependencies for user's code...
2019-05-11T20:31:49.224Z installing to /tmp/5545ccb9
2019-05-11T20:31:49.454Z running user script...
2019-05-11T20:31:49.454Z compiling entrypoint with ncc...
2019-05-11T20:31:49.985Z ncc: Version 0.18.5
ncc: Compiling file index.js
2019-05-11T20:31:50.356Z ncc: Module directory "/tmp/5545ccb9/node_modules/chrome-aws-lambda/source" attempted to require "puppeteer" but could not be resolved, assuming external.
2019-05-11T20:31:50.789Z ncc: Module directory "/tmp/5545ccb9/node_modules/chrome-aws-lambda/source/puppeteer/lib" attempted to require "puppeteer" but could not be resolved, assuming external.
2019-05-11T20:31:50.789Z ncc: Module directory "/tmp/5545ccb9/node_modules/chrome-aws-lambda/source/puppeteer/lib" attempted to require "puppeteer" but could not be resolved, assuming external.
2019-05-11T20:31:51.004Z ncc: Module directory "/tmp/5545ccb9/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
2019-05-11T20:31:51.343Z ncc: Module directory "/tmp/5545ccb9/node_modules/ws/lib" attempted to require "bufferutil" but could not be resolved, assuming external.
2019-05-11T20:31:51.344Z ncc: Module directory "/tmp/5545ccb9/node_modules/ws/lib" attempted to require "utf-8-validate" but could not be resolved, assuming external.
2019-05-11T20:31:51.376Z ncc: Module directory "/tmp/5545ccb9/node_modules/https-proxy-agent/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
2019-05-11T20:32:02.613Z running builder.exports.prepareCache...
2019-05-11T20:37:28.504Z ~~1~~
2019-05-11T20:37:29.641Z ~~~2~~~
2019-05-11T20:37:35.498Z ~~3~~
2019-05-11T20:37:35.501Z ~~4~~~~ true

**Comment by guybedford** [comment] 2019-05-20 07:56
Thanks for posting @zababurinsv, yes we should definitely support Puppeteer.

Pupeteer asset emission support tracking in https://github.com/zeit/webpack-asset-relocator-loader/issues/35.

**Comment by guybedford** [comment] 2019-05-20 08:12
It seems the following approach can be used to support Puppeteer:

```js
const chrome = require("chrome-aws-lambda");
const puppeteer = require("puppeteer-core");

module.exports = async (req, res) => {
  const browser = await puppeteer.launch({
    args: chrome.args,
    executablePath: await chrome.executablePath,
    headless: chrome.headless
  });
};

```

**Comment by styfle** [comment] 2019-05-21 07:17
For a complete application using puppeteer, checkout [og-image](https://github.com/zeit/og-image).

Also note that even if `ncc` supports `puppeteer`, it won't work well in a serverless environment because its 300 MB.

See the [serverless-chrome](https://zeit.co/blog/serverless-chrome) blog post for more information.

**Comment by guybedford** [comment] 2019-05-23 04:57
@styfle thanks for the update here, ok I won't prioritise this fix then for now.

**Comment by AlessandroAnnini** [comment] 2019-07-03 17:01
This is failing for me with the last now/node and with @0.7.3 that was working 40 days ago

this is the error:

```bash
{ Error: Module not found: Error: Can't resolve './lib/api' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './JSHandle' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './LifecycleWatcher' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './DOMWorld' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './JSHandle' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './TimeoutSettings' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './DeviceDescriptors' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './JSHandle' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer-core/lib'
Module not found: Error: Can't resolve './lib/api' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './JSHandle' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './LifecycleWatcher' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './DOMWorld' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './JSHandle' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './TimeoutSettings' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './DeviceDescriptors' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './Events' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
Module not found: Error: Can't resolve './JSHandle' in '/Users/alan/Documents/Projects/scriby-server/node_modules/puppeteer/lib'
    at compiler.close.n (evalmachine.<anonymous>:3:1350338)
    at _promise0.then._result0 (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:13:1)
    at <anonymous>
```

I need to create a pdf so I need `puppeteer-core` and `puppeteer`

**Comment by styfle** [comment] 2019-07-03 20:59
@guybedford I see a regression in `puppeteer-core`.

https://github.com/zeit/og-image/pull/84

Compare the output from 0.18.5 and 0.20.4

## Steps to reproduce

```
https://github.com/zeit/og-image
cd og-image
npx @zeit/ncc@0.18.5 build src/card.ts --source-map -o old
npx @zeit/ncc@0.20.4 build src/card.ts --source-map -o new
ls -lA old
ls -lA new
```

Notice that that new folder is missing the `puppeteer-core` directory.

**Comment by styfle** [comment] 2019-07-08 20:45
@AlessandroAnnini This has been fixed in `@now/node@canary` since we replace ncc. Thanks!

**Comment by zababurinsv** [comment] 2019-07-19 04:26
thank ) 
I recently used github. Poor oriented.
I have one more question today.


Hi. Yesterday my code worked.

server: express
node: module index.mjs
import express from "express";

const app = express();

app.get('*', (req, res) => {
res.status(200).send({key:'test'});
});

export default app

now:
{
"version": 2,
"name": "WebDav",
"builds": [
{ "src": "index.mjs", "use": "@now/node" }
],
"routes": [
{ "src": "/", "dest": "index.mjs" }
]
}

but today it is not work.
What's happened ?

i get an error

SyntaxError: Unexpected identifier
at Module._compile (internal/modules/cjs/loader.js:721:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object. (/tmp/zeit-fun-02176ca18c0dc/___now_launcher.js:21:18)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

How can i use *.mjs with express ?

**Comment by guybedford** [comment] 2019-07-19 21:20
@zababurinsv do you know the line number / code corresponding to that syntax error? That would help a lot to debug further here (the builder upgrade has been reverted for now, but it would be good to know what the issue was).

**Closed** 2019-10-26 20:30 UTC
Labels: bug, package issue, priority
