### ISSUE TITLE
Cannot find module `http`

### ISSUE THREAD

**Issue by tunnckoCore** [zeit/ncc#273] opened 2019-02-07 20:28 UTC
Pretty strange.

```
2019-02-07T20:11:44.377Z  success Already up-to-date.
2019-02-07T20:11:44.380Z  Done in 0.10s.
2019-02-07T20:11:44.868Z  yarn cache v1.12.3
2019-02-07T20:11:44.905Z  warning package.json: No license field
2019-02-07T20:11:44.923Z  success Cleared cache.
2019-02-07T20:11:44.924Z  Done in 0.06s.
2019-02-07T20:11:56.464Z  { Error: Cannot find module 'http'
                              at s (/var/task/user/index.js:20677:262)
                              at /var/task/user/index.js:20677:419
                              at Object.1.http (/var/task/user/index.js:20677:601)
                              at s (/var/task/user/index.js:20677:368)
                              at /var/task/user/index.js:20677:419
                              at Object.3../_read (/var/task/user/index.js:20677:4298)
                              at s (/var/task/user/index.js:20677:368)
                              at e (/var/task/user/index.js:20677:534)
                              at /var/task/user/index.js:20677:554
                              at module.exports.i (/var/task/user/index.js:20677:61) code: 'MODULE_NOT_FOUND' }
2019-02-07T20:11:56.475Z  Error while initializing entrypoint: { Error: Cannot find module 'http'
                              at s (/var/task/user/index.js:20677:262)
                              at /var/task/user/index.js:20677:419
                              at Object.1.http (/var/task/user/index.js:20677:601)
                              at s (/var/task/user/index.js:20677:368)
                              at /var/task/user/index.js:20677:419
                              at Object.3../_read (/var/task/user/index.js:20677:4298)
                              at s (/var/task/user/index.js:20677:368)
                              at e (/var/task/user/index.js:20677:534)
                              at /var/task/user/index.js:20677:554
                              at module.exports.i (/var/task/user/index.js:20677:61) code: 'MODULE_NOT_FOUND' }
2019-02-07T20:11:56.476Z  REPORT RequestId: 5af847b9-7f68-4260-9279-843409332d98	Duration: 4.25 ms	Billed Duration: 100 ms 	Memory Size: 3008 MB	Max Memory Used: 67 MB	

```

With `now.json`

```json
{
  "name": "slack-nda",
  "alias": "slack-nda.now.sh",
  "version": 2,
  "builds": [
    {
      "src": "*.js",
      "use": "@now/node"
    }
  ],
  "env": {
    "SLACK_ACCESS_TOKEN": "@tunnckocorehq-slack-nda-token",
    "SLACK_CLIENT_ID": "@tunnckocorehq-slack-nda-client-id",
    "SLACK_CLIENT_SECRET": "@tunnckocorehq-slack-nda-client-secret"
  }
}

```

I was using `node-fetch`, then switched to `axios` and still fails. Which make sense, since it's built-in module :D But.. I can't understand where this error can come from. Stack traces doesn't help too?

**Comment by rauchg** [comment] 2019-02-07 20:37
Could you please provide some more repro instructions? (gave you some pointers on this on Slack)

**Comment by tunnckoCore** [comment] 2019-02-07 20:38
Yup.

```json
{
  "private": true,
  "name": "slack-nda",
  "version": "0.1.0",
  "main": "index.js",
  "license": "Apache-2.0",
  "devDependencies": {
    "eslint": "^5.13.0",
    "eslint-config-tunnckocore": "^3.0.0",
    "prettier": "^1.16.4"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "dateformat": "^3.0.3",
    "docx-templates": "^2.9.1",
    "fs-extra": "^7.0.1",
    "micro": "^9.3.3",
    "slack": "^11.0.1"
  }
}

```

**Comment by tunnckoCore** [comment] 2019-02-07 21:19
Repo for reproduce: https://github.com/tunnckoCore/slack-nda

Latest deployment: https://slack-zeit-nda-4dcvv9nkp.now.sh/

Once we hit it, it gives us that error.

**Comment by porsager** [comment] 2019-02-07 21:51
I'm seeing the same thing with 0.14.0 and `https`

**Comment by porsager** [comment] 2019-02-07 22:16
Ok, I did a bit more digging, and in my case it was due to a module generating the require string dynamically like `require(url.protocol.slice(0, -1))`. It worked fine after changing it to this:
```
url.protocol === 'https:' ? require('https') : require('http')
```

I don't know if this is something ncc is able to handle?

**Comment by tunnckoCore** [comment] 2019-02-08 01:02
Whatever it is, it does not make sense to error, since both modules exist in nodejs :D Pretty strange error. Debugging isn't quite easy because everything is bundled and not in your machine so you can't follow the stacktrace.

But anyway, I couldn't find what was wrong, but continued with refactoring and it disappeared.

**Comment by rauchg** [comment] 2019-02-12 19:27
@porsager would you mind submitting a PR with that minimal test case?

**Comment by guybedford** [comment] 2019-02-14 00:44
I've added a fix here in https://github.com/zeit/webpack-asset-relocator-loader/commit/590d2abed881e1c25d6509bf787ada99817ab077. Will post the update PR shortly.

**Comment by porsager** [comment] 2019-02-14 07:55
@rauchg sorry, seems @guybedford beat me to it :) Nice job!

And thank you for an awesome tool. This really cleans up our distributed apps!

**Comment by styfle** [comment] 2019-02-15 16:05
Fixed in ncc@0.15.1

**Closed by styfle** 2019-02-15 16:05 UTC

**Comment by EnixCoda** [comment] 2019-03-01 02:45
Is the fix released? I'm still getting this error.

**Comment by styfle** [comment] 2019-03-01 03:32
@EnixCoda It was released in `@now/node@canary` but not the stable `@now/node` yet.

**Comment by EnixCoda** [comment] 2019-03-01 04:08
@styfle Thanks for replying!
I tried `@now/node@canary` and got another error: `Unable to import module 'launcher'`.
Maybe I'd better wait for next stable release...

BTW, how can I subscribe to release updates?

**Comment by tunnckoCore** [comment] 2019-03-01 10:01
@enixcoda, github recently added such feature, click the watch button and then "releases only".

**Comment by EnixCoda** [comment] 2019-03-01 10:16
@tunnckoCore I see, thank you!

**Comment by styfle** [comment] 2019-03-01 14:36
@EnixCoda Can you create a new issue and provide the source code to reproduce this bug? Thanks!
